"""ProducerNode — the in-process equivalent of Train_IoT_data_producer.

Reproduces ``produce.py``'s two generation threads (``thread_anomalie`` and
``thread_normali``) faithfully, driving the *same* physically-grounded
``Train`` simulator vendored in :mod:`offline_simulation.simulator`:

* the live stream (``{vehicle}_anomalies`` / ``{vehicle}_normal_data``) carries
  NORMAL, ANOMALY or ATTACK observations. ANOMALY flips to ATTACK exactly when
  the vehicle is "infected" — offline that flag is owned by the orchestrator
  instead of a Flask backdoor, but the branch is identical
  (``get_status_robust() == 'INFECTED'``).
* the adversarial eval stream (``{vehicle}_eval_anomalies``) is generated by a
  second, independently-seeded ``Train`` with ``adversarial=True`` and feeds the
  consumer's adversarial-training buffers.

The Kafka producer is replaced by :class:`MessageBus`; everything else — the
per-vehicle noise knobs (Mp_std/Bp_std), the decoupled eval noise
(eval_Mp_std/eval_Bp_std), the seed offset of +1 for the eval train, and the
lognormal inter-arrival durations under ``time_emulation`` — matches the
platform.
"""

import time
import types
import logging
import threading

import numpy as np

from .simulator import Train, EventType

HEALTHY = "HEALTHY"
INFECTED = "INFECTED"

# The producer decorates each observation with the same bookkeeping columns the
# real producer adds; the consumer deletes all of them (columns_to_delete)
# before tensorising, so only their presence — not their value — matters.
_META_COLUMNS = ['Durata', 'Flotta', 'Veicolo', 'Test',
                 'Timestamp', 'Timestamp chiusura']


def _round4(d):
    return {k: (round(v, 4) if isinstance(v, (int, float)) else v) for k, v in d.items()}


class ProducerNode:
    def __init__(self, vehicle_name, config, bus, get_status):
        """
        Parameters
        ----------
        vehicle_name : str
        config : dict
            The producer config payload (see config_builders.build_producer_config).
        bus : MessageBus
        get_status : callable(vehicle_name) -> "HEALTHY"|"INFECTED"
            In-process replacement for the dashboard's vehicle-status endpoint;
            the orchestrator owns the attack state.
        """
        self.vehicle_name = vehicle_name
        self.config = config
        self.bus = bus
        self._get_status = get_status

        self.logger = logging.getLogger(f'[{vehicle_name}_PROD]')

        self.mu_anomalies = float(config.get('mu_anomalies', 0.157))
        self.mu_normal = float(config.get('mu_normal', 0.117))
        self.alpha = float(config.get('alpha', 0.05))
        self.beta = float(config.get('beta', 1.9))
        self.time_emulation = bool(config.get('time_emulation', True))

        seed = config.get('seed', None)
        # Dedicated RNG for the lognormal inter-arrival durations (scipy's
        # lognorm(s=sigma, scale=exp(mu)) == numpy lognormal(mean=mu, sigma)).
        self._dur_rng = np.random.default_rng(None if seed is None else seed + 100)

        # Build the two Train simulators exactly like start_producer_threads.
        ns_main = types.SimpleNamespace(**config)
        ns_eval = types.SimpleNamespace(**config)
        if seed is not None:
            ns_eval.seed = seed + 1
        self.virtual_train = Train(ns_main)
        self.eval_virtual_train = Train(ns_eval)
        eval_mp = config.get('eval_Mp_std', None)
        eval_bp = config.get('eval_Bp_std', None)
        if eval_mp is not None:
            self.eval_virtual_train.Mp_std = eval_mp
        if eval_bp is not None:
            self.eval_virtual_train.Bp_std = eval_bp

        self.produced_records = 0
        self.produced_attacks = 0
        self.produced_anomalies = 0
        self.produced_diagnostics = 0

        self._stop = False
        self._threads = []

    # -- lifecycle ---------------------------------------------------------
    def start(self):
        self._stop = False
        self.bus.create_topic(f"{self.vehicle_name}_anomalies")
        self.bus.create_topic(f"{self.vehicle_name}_eval_anomalies")
        self.bus.create_topic(f"{self.vehicle_name}_normal_data")
        self._threads = [
            threading.Thread(target=self._thread_anomalie, daemon=True,
                             name=f"{self.vehicle_name}_anom"),
            threading.Thread(target=self._thread_normali, daemon=True,
                             name=f"{self.vehicle_name}_norm"),
        ]
        for t in self._threads:
            t.start()
        self.logger.info(f"Producer started for vehicle {self.vehicle_name}")

    def stop(self):
        self._stop = True
        for t in self._threads:
            t.join(timeout=5)
        self._threads = []
        self.logger.info(f"Producer stopped for vehicle {self.vehicle_name}")

    # -- helpers -----------------------------------------------------------
    def _get_status_robust(self):
        return self._get_status(self.vehicle_name)

    def _produce(self, data, topic):
        self.bus.produce(topic, data)
        self.produced_records += 1
        if self.produced_records % 500 == 0:
            self.logger.info(
                f"sent {self.produced_records} records: {self.produced_attacks} attacks, "
                f"{self.produced_anomalies} anomalies, {self.produced_diagnostics} diagnostics.")

    def _add_meta(self, d, durata):
        d['Durata'] = durata
        d['Flotta'] = 'ETR700'
        d['Veicolo'] = self.vehicle_name
        d['Test'] = 'N'
        now = time.time()
        d['Timestamp'] = str(now)
        d['Timestamp chiusura'] = str(now + durata)
        return d

    # -- generation threads (mirror produce.py) ----------------------------
    def _thread_anomalie(self):
        self.logger.info(f"Starting anomalies thread for vehicle: {self.vehicle_name}")
        media = self.mu_anomalies * self.alpha
        sigma = 1 * self.beta
        topic = f"{self.vehicle_name}_anomalies"
        eval_topic = f"{self.vehicle_name}_eval_anomalies"

        while not self._stop:
            if self._get_status_robust() == INFECTED:
                event = EventType.ATTACK
                self.produced_attacks += 1
            else:
                event = EventType.ANOMALY
                self.produced_anomalies += 1

            synthetic = self.virtual_train.step(event)
            eval_synth = self.eval_virtual_train.step(event, adversarial=True)

            durata = float(self._dur_rng.lognormal(mean=np.log(media), sigma=sigma))
            data = self._add_meta(_round4(synthetic), durata)
            eval_data = self._add_meta(_round4(eval_synth), durata)

            self._produce(data, topic)
            self._produce(eval_data, eval_topic)
            if self.time_emulation:
                time.sleep(durata)

    def _thread_normali(self):
        self.logger.info(f"Starting normal-data thread for vehicle: {self.vehicle_name}")
        media = self.mu_normal * self.alpha
        sigma = 1 * self.beta
        topic = f"{self.vehicle_name}_normal_data"

        while not self._stop:
            synthetic = self.virtual_train.step(EventType.NORMAL)
            # The eval train is still stepped for NORMAL to keep its RNG stream
            # aligned with the live train, exactly as produce.py does (the
            # result is intentionally discarded).
            _ = self.eval_virtual_train.step(EventType.NORMAL, adversarial=True)

            durata = float(self._dur_rng.lognormal(mean=np.log(media), sigma=sigma))
            data = self._add_meta(_round4(synthetic), durata)

            self._produce(data, topic)
            self.produced_diagnostics += 1
            if self.time_emulation:
                time.sleep(durata)

    # -- status ------------------------------------------------------------
    def status(self):
        return {
            'vehicle': self.vehicle_name,
            'records_produced': self.produced_records,
            'attacks_produced': self.produced_attacks,
            'anomalies_produced': self.produced_anomalies,
            'diagnostics_produced': self.produced_diagnostics,
            'under_attack': self._get_status_robust() == INFECTED,
        }
