
default_vehicle_config:

  # adversarial_training: True
  # Additional environment variables for every vehicle container (both producer and consumer)
  common_env_vars:
    http_proxy: http://proxy.uninsubria.it:3128
    https_proxy: http://proxy.uninsubria.it:3128


vehicles:
  - angela:
      Mp_std: 0
      Bp_std: 0
  
  - bob:
      Mp_std: 1
      Bp_std: 1
  
  - claude:
      Mp_std: 2
      Bp_std: 2

  - daniel:
      Mp_std: 3
      Bp_std: 3