
default_vehicle_config:

  # Additional environment variables for every vehicle container (both producer and consumer)
  common_env_vars:
    http_proxy: http://proxy.uninsubria.it:3128
    https_proxy: http://proxy.uninsubria.it:3128