wandb:
  run_name: fed_AVG

federated_learning:
  aggregation_strategy: fedavg    # fedavg, fedyogi
  aggregation_interval_secs: 20     


default_consumer_config:
  weights_push_freq_seconds: 120
  weights_pull_freq_seconds: 120
  learning_rate: 0.002