wandb:
  run_name: SW

security_manager:
  probe_metrics:
    - RTT
    - INBOUND
    - OUTBOUND

anomaly_detection:
  h_dim: 400
  num_layers: 4
  layer_norm: True


attack:
  automatic_attack_interval_secs: 8
